# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: dsh
        name: Update all DSH index.md
        entry: python hooks.py
        language: python
