site_name: Data Scientist Hub
site_url: https://a-slice-of-py.github.io/data-scientist-hub
site_description: "A data scientist knowledge center."
repo_url: https://github.com/a-slice-of-py/data-scientist-hub
repo_name: a-slice-of-py/dsh

theme:
  favicon: assets/dsh_minimal.png
  logo: assets/dsh_minimal.png
  icon:
    repo: fontawesome/brands/github
    tag:
      aws: simple/amazonaws
      db: material/database
      devops: material/source-branch-sync
      iac: simple/awsorganizations
      ita: material/translate
      ml: material/brain
      open: material/open-source-initiative
      or: fontawesome/solid/gears
      py: simple/python
      streamlit: simple/streamlit
  name: "material"
  palette:
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode 
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.share
    - search.highlight
    - toc.follow

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      title: What's here
      permalink: True
      toc_depth: 3 # remove for default 6

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.critic  
  - pymdownx.snippets

plugins:
  - search
  - awesome-pages
  - blog:
      authors: true
      post_excerpt: required
  - tags:
      tags_file: tags.md
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

extra:
  tags:
    AWS: aws
    Database: db
    DevOps: devops
    IaC: iac
    ITA: ita
    Machine Learning: ml
    Open Source: open
    OR: or
    Python: py
    Streamlit: streamlit
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/a-slice-of-py
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://it.linkedin.com/in/silviolugaro
      name: Linkedin

copyright: Copyright &copy; 2024 Silvio Lugaro