site_name: Data Scientist Hub
site_url: https://a-slice-of-py.github.io/data-scientist-hub
site_description: "A data scientist knowledge center."
repo_url: https://github.com/a-slice-of-py/data-scientist-hub
repo_name: a-slice-of-py/dsh

theme:
  favicon: assets/dsh_minimal.png
  logo: assets/dsh_minimal.png
  icon:
    repo: fontawesome/brands/github
  name: "material"
  font:
    text: Readex Pro
  palette:
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: blue grey
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode 
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.share

markdown_extensions:
  - attr_list
  - pymdownx.progressbar
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.arithmatex
  # - pymdownx.arithmatex:
  #     generic: True
  - admonition
  - footnotes
  - toc:
      title: What's here
      permalink: True
      toc_depth: 3 # remove for default 6

plugins:
  - search
  - awesome-pages
  - blog:
      format: "[%Y/%m/%d]"
  - tags:
      tags_file: tags.md

extra_css:
  - stylesheets/extra.css
  - stylesheets/tasklist.css

extra_javascript:
  - javascript/config.js
  - javascript/MathJax.min.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/a-slice-of-py
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://it.linkedin.com/in/silviolugaro
      name: Linkedin

copyright: Copyright &copy; 2022 Silvio Lugaro