site_name: Data Scientist Hub
site_url: https://a-slice-of-py.github.io/data-scientist-hub
repo_url: https://github.com/a-slice-of-py/data-scientist-hub
repo_name: a-slice-of-py/dsh

theme:
  favicon: assets/dsh_minimal.png
  logo: assets/dsh_minimal.png
  icon:
    repo: fontawesome/brands/github
  name: "material"
  palette:
    scheme: slate
    primary: amber
    accent: orange
  features:
    - navigation.tabs

markdown_extensions:
  - attr_list
  - pymdownx.progressbar
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.arithmatex
  - admonition
  - footnotes
  - toc:
      permalink: True

plugins:
  - search
  - mkdocstrings
  - awesome-pages
  - blog:
      format: "[%Y/%m/%d]"

extra_css:
  - css/extra.css